# Generated by Django 5.0.3 on 2024-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metamaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wm', models.DecimalField(decimal_places=3, help_text='Width and height of SRR cell', max_digits=9, verbose_name='Wm')),
                ('W0m', models.DecimalField(decimal_places=3, help_text='Gap between rings', max_digits=7, verbose_name='W0m')),
                ('dm', models.DecimalField(decimal_places=3, help_text='Distance between rings', max_digits=7, verbose_name='dm')),
                ('tm', models.DecimalField(decimal_places=3, help_text='Width of the rings', max_digits=9, verbose_name='tm')),
                ('rows', models.DecimalField(decimal_places=1, help_text='Number of SRR cells in a array', max_digits=3, verbose_name='rows')),
                ('Xa', models.DecimalField(decimal_places=3, help_text='Distance between antenna patch and array', max_digits=9, verbose_name='Xa')),
                ('Ya', models.DecimalField(decimal_places=3, help_text='Distance between SRR cells in the array', max_digits=9, verbose_name='Ya')),
                ('gain', models.DecimalField(decimal_places=7, help_text='Antenna gain', max_digits=9, verbose_name='gain')),
                ('vswr', models.DecimalField(decimal_places=7, help_text='Voltage Standing Wave Ratio of the antenna', max_digits=9, verbose_name='vswr')),
                ('bandwidth', models.DecimalField(decimal_places=7, help_text='Bandwidth of the antenna', max_digits=10, verbose_name='bandwidth')),
                ('s', models.DecimalField(decimal_places=7, default=0, help_text='Return Loss (S11) of the antenna', max_digits=10, verbose_name='s')),
                ('pr', models.DecimalField(decimal_places=7, default=0, help_text='Power radiated by antenna', max_digits=9, verbose_name='pr')),
                ('p0', models.DecimalField(decimal_places=7, default=0, help_text='Power accepted by antenna', max_digits=9, verbose_name='p0')),
            ],
        ),
    ]
